apiVersion: apps/v1
kind: Deployment

metadata:
  name: mecaniqa-mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mecaniqa-mysql

  template:
    metadata:
      labels:
        app: mecaniqa-mysql

    spec:
      containers:
        - name: mysql
          image: mecaniqa-belo-horizonte-db:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"

            - name: MYSQL_DATABASE
              value: "mecaniqa"